id: JoeSecurityTestPlaybook
version: 24
name: JoeSecurityTestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 78c271cb-d8af-41fd-8fda-a63ffdb3a88e
    type: start
    task:
      id: 78c271cb-d8af-41fd-8fda-a63ffdb3a88e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 65
        }
      }
  "1":
    id: "1"
    taskid: 3e175f62-728f-4863-809e-08c04f75646d
    type: regular
    task:
      id: 3e175f62-728f-4863-809e-08c04f75646d
      version: -1
      name: Start fresh
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 225
        }
      }
  "2":
    id: "2"
    taskid: 136469b7-cc7b-49cf-8ba9-44a06b641931
    type: regular
    task:
      id: 136469b7-cc7b-49cf-8ba9-44a06b641931
      version: -1
      name: Validate instance is working
      script: Joe Security|||joe-is-online
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 400
        }
      }
  "3":
    id: "3"
    taskid: f8df841b-1ed1-4a02-842b-602586d42184
    type: regular
    task:
      id: f8df841b-1ed1-4a02-842b-602586d42184
      version: -1
      name: Analyse a file using a url without waiting
      script: Joe Security|||joe-analysis-submit-sample
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      comments: {}
      file_id: {}
      internet-access: {}
      sample_url:
        simple: http://www.tutorialspoint.com/java/java_tutorial.pdf
      should_wait: {}
      systems: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "4":
    id: "4"
    taskid: 1a0a19dd-5d4d-4412-871b-cbd85a954ba2
    type: regular
    task:
      id: 1a0a19dd-5d4d-4412-871b-cbd85a954ba2
      version: -1
      name: Analyse a url without waiting
      script: Joe Security|||joe-analysis-submit-url
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      comments: {}
      should_wait:
        simple: "False"
      systems: {}
      url:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
  "5":
    id: "5"
    taskid: 12077a28-82e3-4e50-86a8-beec870e9342
    type: regular
    task:
      id: 12077a28-82e3-4e50-86a8-beec870e9342
      version: -1
      name: Get info on the file analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
  "6":
    id: "6"
    taskid: 1b5701d0-bd7a-4bb1-8261-55c7fb3c6409
    type: regular
    task:
      id: 1b5701d0-bd7a-4bb1-8261-55c7fb3c6409
      version: -1
      name: Get info on the URL analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[1].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
  "7":
    id: "7"
    taskid: 5f17b470-20c9-4f8f-8e65-b6df2390e874
    type: regular
    task:
      id: 5f17b470-20c9-4f8f-8e65-b6df2390e874
      version: -1
      name: Analyse url with polling
      script: Joe Security|||joe-analysis-submit-url
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      comments: {}
      internet-access:
        simple: "False"
      should_wait:
        simple: "True"
      systems: {}
      url:
        simple: http://www.tutorialspoint.com/java/java_tutorial.pdf
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 750
        }
      }
  "9":
    id: "9"
    taskid: dd4587a0-c399-43a2-8c68-4d26c4c11b23
    type: regular
    task:
      id: dd4587a0-c399-43a2-8c68-4d26c4c11b23
      version: -1
      name: Create sample file
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      data:
        simple: qwerty
      entryId: {}
      filename:
        simple: zaq.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1100
        }
      }
  "10":
    id: "10"
    taskid: ba14db75-ccd1-4571-89c4-0be8c92bc335
    type: regular
    task:
      id: ba14db75-ccd1-4571-89c4-0be8c92bc335
      version: -1
      name: Run sample with file
      script: Joe Security|||joe-analysis-submit-sample
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      comments:
        simple: for next run
      file_id:
        complex:
          root: File
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: zaq.txt
          transformers:
          - operator: general.getField
            args:
              field:
                value:
                  simple: EntryID
      internet-access: {}
      sample_url: {}
      should_wait:
        simple: "True"
      systems: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1275
        }
      }
  "11":
    id: "11"
    taskid: b14e8d4c-db43-41eb-805a-2c129109400c
    type: regular
    task:
      id: b14e8d4c-db43-41eb-805a-2c129109400c
      version: -1
      name: Search command
      script: Joe Security|||joe-search
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "13"
      - "14"
      - "15"
    scriptarguments:
      query:
        simple: for next run
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 575
        }
      }
  "13":
    id: "13"
    taskid: f13efe19-3484-4cf6-8c13-cf76b156cf17
    type: regular
    task:
      id: f13efe19-3484-4cf6-8c13-cf76b156cf17
      version: -1
      name: Download fie Report - HTML
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      type:
        simple: html
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 750
        }
      }
  "14":
    id: "14"
    taskid: 96cc4b19-4a75-41da-8872-643ac565484b
    type: regular
    task:
      id: 96cc4b19-4a75-41da-8872-643ac565484b
      version: -1
      name: Download url Report - PDF
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: pdf
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 750
        }
      }
  "15":
    id: "15"
    taskid: b760fed3-67dd-4e56-8d9b-5a0758badb3e
    type: regular
    task:
      id: b760fed3-67dd-4e56-8d9b-5a0758badb3e
      version: -1
      name: Download url Report -JSON
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: json
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 750
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1320,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
