id: minemeld_test
version: 51
name: Minemeld Test
description: This is a playbook test for Palo Alto minemeld Node's indicators integration.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 8bf8638f-cdca-4016-8c25-617eda6af6ee
    type: start
    task:
      id: 8bf8638f-cdca-4016-8c25-617eda6af6ee
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: b660b6c5-d807-4f4a-8bd1-1aae352e7f96
    type: regular
    task:
      id: b660b6c5-d807-4f4a-8bd1-1aae352e7f96
      version: -1
      name: Add indicator to miner
      script: Palo Alto Minemeld|||minemeld-add-to-miner
      type: regular
      iscommand: true
      brand: Palo Alto Minemeld
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      comment:
        simple: test comment
      miner:
        simple: Suspicious
      share-level: {}
      type:
        simple: IPv4
      value:
        simple: 6.6.6.6
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 369
        }
      }
    note: false
  "2":
    id: "2"
    taskid: c9fd9af2-509c-4f56-8e23-cc68267dbdc2
    type: regular
    task:
      id: c9fd9af2-509c-4f56-8e23-cc68267dbdc2
      version: -1
      name: Delete Context
      description: Clear context before process starts
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 324b4c84-0b80-4350-87e7-4f23e9d7ad16
    type: regular
    task:
      id: 324b4c84-0b80-4350-87e7-4f23e9d7ad16
      version: -1
      name: Retrieve indicator from miner's list
      script: Palo Alto Minemeld|||minemeld-get-item-from-list
      type: regular
      iscommand: true
      brand: Palo Alto Minemeld
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      item:
        simple: 6.6.6.6
      miner:
        simple: Suspicious
      type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: b4b55e9d-09d9-44ca-8faa-20ca62a20722
    type: condition
    task:
      id: b4b55e9d-09d9-44ca-8faa-20ca62a20722
      version: -1
      name: Test if indicator exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    scriptarguments:
      value:
        complex:
          root: Minemeld
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Minemeld.indicator
                iscontext: true
              right:
                value:
                  simple: asdas
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: MineMeld
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: MineMeld.Item.indicator
                      iscontext: true
                    right:
                      value:
                        simple: 6.6.6.6
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
  "5":
    id: "5"
    taskid: e3993ce4-7232-417d-8952-cf843450ad40
    type: regular
    task:
      id: e3993ce4-7232-417d-8952-cf843450ad40
      version: -1
      name: Remove indicator from miner
      script: Palo Alto Minemeld|||minemeld-remove-from-miner
      type: regular
      iscommand: true
      brand: Palo Alto Minemeld
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      miner:
        simple: Suspicious
      type:
        simple: IPv4
      value:
        simple: 6.6.6.6
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
  "6":
    id: "6"
    taskid: c0e90b3d-e1b2-4015-8f2c-f6f6c3179fb4
    type: regular
    task:
      id: c0e90b3d-e1b2-4015-8f2c-f6f6c3179fb4
      version: -1
      name: Test failed
      scriptName: ThrowException
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      error:
        simple: This test has failed, indicator was not found.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 349056ae-7e73-4add-83ab-1a8046e5af49
    type: condition
    task:
      id: 349056ae-7e73-4add-83ab-1a8046e5af49
      version: -1
      name: Test if indicator exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "8"
    scriptarguments:
      value:
        complex:
          root: Minemeld
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Minemeld.indicator
                iscontext: true
              right:
                value:
                  simple: asdas
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: MineMeld
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: Minemeld.Miner.indicator
                      iscontext: true
                    right:
                      value:
                        simple: 6.6.6.6
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1419
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 0324f8c7-0e4c-4f70-8c0a-c71dccc7356a
    type: regular
    task:
      id: 0324f8c7-0e4c-4f70-8c0a-c71dccc7356a
      version: -1
      name: Test Failed - Could not delete indicator / indicator still in context
      scriptName: ThrowException
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      error:
        simple: Test Failed - Could not delete indicator
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 298db46f-28c7-49e4-8447-05cfea5354de
    type: title
    task:
      id: 298db46f-28c7-49e4-8447-05cfea5354de
      version: -1
      name: Test finished successfuly
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 58,
          "y": 2305
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 5ef7bf8b-7559-470d-877d-3adbbeb457d2
    type: regular
    task:
      id: 5ef7bf8b-7559-470d-877d-3adbbeb457d2
      version: -1
      name: Retrieve miner's indicators list
      script: Palo Alto Minemeld|||minemeld-retrieve-list
      type: regular
      iscommand: true
      brand: Palo Alto Minemeld
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      all: {}
      miner:
        simple: Suspicious
      type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 9fbf712c-a4d2-4ce9-851a-d989a62b0df2
    type: regular
    task:
      id: 9fbf712c-a4d2-4ce9-851a-d989a62b0df2
      version: -1
      name: Delete Context
      description: Clear context before process starts
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
  "15":
    id: "15"
    taskid: 8d0a00af-f482-4936-8005-c96af02033c8
    type: regular
    task:
      id: 8d0a00af-f482-4936-8005-c96af02033c8
      version: -1
      name: Delete Context
      description: Clear context before process starts
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 58,
          "y": 1595
        }
      }
    note: false
  "16":
    id: "16"
    taskid: 4fdccd0d-c0d1-4aa3-8cc8-dd082f1a21a5
    type: regular
    task:
      id: 4fdccd0d-c0d1-4aa3-8cc8-dd082f1a21a5
      version: -1
      name: Check IP
      script: Palo Alto Minemeld|||ip
      type: regular
      iscommand: true
      brand: Palo Alto Minemeld
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      ip:
        simple: 7.7.7.7
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 58,
          "y": 1949
        }
      }
    note: false
  "17":
    id: "17"
    taskid: 3c3a3427-190d-4007-8aca-8c6e5965e629
    type: regular
    task:
      id: 3c3a3427-190d-4007-8aca-8c6e5965e629
      version: -1
      name: Add IP indicator to miner
      script: Palo Alto Minemeld|||minemeld-add-to-miner
      type: regular
      iscommand: true
      brand: Palo Alto Minemeld
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      comment:
        simple: test ip 7777
      miner:
        simple: Malicious
      type:
        simple: IPv4
      value:
        simple: 7.7.7.7
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 58,
          "y": 1779
        }
      }
    note: false
  "18":
    id: "18"
    taskid: 5f2b5def-7727-4e8f-8e96-e2e49b30b45d
    type: condition
    task:
      id: 5f2b5def-7727-4e8f-8e96-e2e49b30b45d
      version: -1
      name: Test if indicator exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "19"
      "yes":
      - "9"
    scriptarguments:
      value:
        complex:
          root: Minemeld
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Minemeld.indicator
                iscontext: true
              right:
                value:
                  simple: asdas
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: IP
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: IP.MineMeld.Item.indicator
                      iscontext: true
                    right:
                      value:
                        simple: 7.7.7.7
                accessor: MineMeld.Item
            iscontext: true
    view: |-
      {
        "position": {
          "x": 58,
          "y": 2122
        }
      }
    note: false
  "19":
    id: "19"
    taskid: 6b9ac802-fbdb-4921-8f2d-2b7ea0efd546
    type: regular
    task:
      id: 6b9ac802-fbdb-4921-8f2d-2b7ea0efd546
      version: -1
      name: Test Failed - Could not delete indicator / indicator still in context
      scriptName: ThrowException
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      error:
        simple: Test Failed - Could not delete indicator
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 483,
          "y": 2236
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {
      "4_6_#default#": 0.61,
      "7_8_yes": 0.9
    },
    "paper": {
      "dimensions": {
        "height": 2320,
        "width": 1017,
        "x": 58,
        "y": 50
      }
    }
  }
inputs: []
outputs: []