id: ATD - Detonate File_copy
version: -1
name: ATD - Detonate File_copy
description: Detonate a file through McAfee ATD
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bb01d4bd-76d4-4d60-897b-d169fc413163
    type: start
    task:
      id: bb01d4bd-76d4-4d60-897b-d169fc413163
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 37
        }
      }
  "5":
    id: "5"
    taskid: ade8898b-5f2e-4ba1-8989-2977e4a58003
    type: condition
    task:
      id: ade8898b-5f2e-4ba1-8989-2977e4a58003
      version: -1
      name: Is ATD Available?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "7"
    scriptarguments:
      value:
        simple: modules.brand(val==='McAfee Advanced Threat Defense')
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 175
        }
      }
  "6":
    id: "6"
    taskid: 35ddeef4-f49f-493d-8679-80624dd4d1d8
    type: title
    task:
      id: 35ddeef4-f49f-493d-8679-80624dd4d1d8
      version: -1
      name: End
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 272,
          "y": 1108
        }
      }
  "7":
    id: "7"
    taskid: cc6b3924-e309-4c30-8caf-d9fed896acad
    type: condition
    task:
      id: cc6b3924-e309-4c30-8caf-d9fed896acad
      version: -1
      name: Is there a file to detonate?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "8"
    scriptarguments:
      value:
        simple: ${inputs.EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -21,
          "y": 392
        }
      }
  "8":
    id: "8"
    taskid: 1f223a64-b600-4631-815b-f9a929f3a3ac
    type: regular
    task:
      id: 1f223a64-b600-4631-815b-f9a929f3a3ac
      version: -1
      name: ATD - Detonate File
      script: McAfee Advanced Threat Defense|||detonate-file
      type: regular
      iscommand: true
      brand: McAfee Advanced Threat Defense
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      format: {}
      timeout: {}
      upload:
        simple: ${inputs.EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -162,
          "y": 606
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "5_6_no": 0.1
    },
    "paper": {
      "dimensions": {
        "height": 1136,
        "width": 814,
        "x": -162,
        "y": 37
      }
    }
  }
inputs:
- key: EntryID
  value:
    simple: ${File.EntryID}
  required: false
  description: the EntryID of the file to detonate
outputs: []
